### ISSUE TITLE
2.x.x todo list

### ISSUE THREAD

**Issue by ygongdev** [adopted-ember-addons/ember-sortable#281]
This is used to track progress to `2.x.x`

- [x] Remove mixin -> #270 
- [x] Test suite upgrade -> #271 
- [x] SendAction deprecation -> #282 
- [x] Closest polyfill for IE -> #280 
~~- [ ] Ember upgrade~~
- [x] Converting components into closure components
- [x] Migration Guide
- [x] Keyboard support
- [x] Visual Indicators
- [x] Screen reader announcement

**Comment by ygongdev** [comment]
Done

**Comment by gtb104** [comment]
Was 2.0 published to NPM? It's still showing 1.12.10 as the latest.

**Comment by ygongdev** [comment]
@gtb104 sorry about that, just got the publish access, it’s published now!
